<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filesendersvc.proto

namespace Revad\Filesender;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>revad.filesender.CompleteFileRequest</code>
 */
class CompleteFileRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string file = 1;</code>
     */
    protected $file = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $file
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Filesendersvc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string file = 1;</code>
     * @return string
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * Generated from protobuf field <code>string file = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFile($var)
    {
        GPBUtil::checkString($var, True);
        $this->file = $var;

        return $this;
    }

}

