<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filesendersvc.proto

namespace Revad\Filesender;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>revad.filesender.ReadChunkRequest</code>
 */
class ReadChunkRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string file = 1;</code>
     */
    private $file = '';
    /**
     * Generated from protobuf field <code>int64 offset = 2;</code>
     */
    private $offset = 0;
    /**
     * Generated from protobuf field <code>int64 length = 3;</code>
     */
    private $length = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $file
     *     @type int|string $offset
     *     @type int|string $length
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Filesendersvc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string file = 1;</code>
     * @return string
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * Generated from protobuf field <code>string file = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFile($var)
    {
        GPBUtil::checkString($var, True);
        $this->file = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 offset = 2;</code>
     * @return int|string
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Generated from protobuf field <code>int64 offset = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkInt64($var);
        $this->offset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 length = 3;</code>
     * @return int|string
     */
    public function getLength()
    {
        return $this->length;
    }

    /**
     * Generated from protobuf field <code>int64 length = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLength($var)
    {
        GPBUtil::checkInt64($var);
        $this->length = $var;

        return $this;
    }

}

