<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filesendersvc.proto

namespace Revad\Filesender;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>revad.filesender.WriteChunkResponse</code>
 */
class WriteChunkResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 error = 1;</code>
     */
    protected $error = 0;
    /**
     * Generated from protobuf field <code>int64 offset = 2;</code>
     */
    protected $offset = 0;
    /**
     * Generated from protobuf field <code>int64 written = 3;</code>
     */
    protected $written = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $error
     *     @type int|string $offset
     *     @type int|string $written
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Filesendersvc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 error = 1;</code>
     * @return int
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Generated from protobuf field <code>int32 error = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkInt32($var);
        $this->error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 offset = 2;</code>
     * @return int|string
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Generated from protobuf field <code>int64 offset = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkInt64($var);
        $this->offset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 written = 3;</code>
     * @return int|string
     */
    public function getWritten()
    {
        return $this->written;
    }

    /**
     * Generated from protobuf field <code>int64 written = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWritten($var)
    {
        GPBUtil::checkInt64($var);
        $this->written = $var;

        return $this;
    }

}

